{% set name = "aiocsv" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiocsv-{{ version }}.tar.gz
  sha256: f3877e5ef493616a1e0c1365744bbff89184b6f84e9a70859fe319d92060079a

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python
    - typing_extensions

test:
  imports:
    - aiocsv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MKuranowski/aiocsv
  summary: Asynchronous CSV reading/writing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
